[SOLUTION]
# Framework used to train the model
FRAMEWORK = pytorch

# Whether to retrain the model
RETRAIN = True

# Whether to validate the model after training
VALIDATE = True

[MODEL]

# Model architecture name
NAME = MobilenetV2

# Whether to use pre-trained weights
PRE_TRAIN = True

# Whether to use transfer learning
TRANSFER_LEARNING = True

# Input size for the model
INPUT_SIZE = 160

# Number of classes in the dataset
NUM_CLASSES = 3

[DATASET]

# The name of the class in "..\src\imx500_zoo\datasets\card_classification.py"
NAME = CardClassification

# Whether to use data augmentation defined in "..\src\imx500_zoo\datasets\card_classification.py"
AUGMENTATION = True

[TRAINER]

# Trainer class name
NAME = ClassificationTrainer
BATCH_SIZE = 10
NUM_WORKERS = 15
NUM_EPOCHS = 5
LEARNING_RATE = 1e-3

[QUANTIZER]

# Quantization method
NAME = MctTorch
BATCH_SIZE = 2
CALIB_ITERATIONS = 10
Z_THRESHOLD = 16

[VALIDATOR]

# Validator for classification models
NAME = OnnxClassificationValidator