[SOLUTION]

# Framework used to train the model
FRAMEWORK = keras

# Whether to retrain the model
RETRAIN = True

# Whether to validate the model after training
VALIDATE = True


[MODEL]

# Model architecture name
NAME = NanodetPlus

# Input size for the model
INPUT_SIZE = 416

# Scale factor for the model
SCALE_FACTOR = 1.5

# Bottleneck ratio for the model
BOTTLENECK_RATIO = 0.5

# Number of feature channels
FEATURE_CHANNELS = 128

# Number of classes in the dataset
CLASS_NUM = 3

# Mean values for input normalization
MEAN = [103.53, 116.28, 123.675]

# Standard deviation values for input normalization
STD = [57.375, 57.12, 58.395]

# Model Architecture
BACKBONE_SIZE = 1.5x
BACKBONE_ACTIVATION = LeakyReLU
FPN_KERNEL_SIZE = 5
FPN_USE_DEPTHWISE = True
FPN_NUM_EXTRA_LEVEL = 1

[DATASET]

# The name of the class in "..\src\imx500_zoo\datasets\card_detection.py"
NAME = CardDetection

# Whether to use the data augmentation defined in "..\third_party\nanodet\card_detection.py"
AUGMENTATION = True


[TRAINER]

# Trainer class name
NAME = NanodetPlusTrainer

# Batch size for training
BATCH_SIZE = 10

# Number of workers for data loading
NUM_WORKERS = 15

# Number of epochs for training
NUM_EPOCHS = 20

# Learning rate for training
LEARNING_RATE = 1e-3

# Training configuration file customized for card detection dataset
CONFIG = ./config/nanodet-plus-m-1.5x_416_card.yml

[LOSS]
# Quality Focal Loss
QFL_BETA = 2.0
QFL_WEIGHT = 1.0

# Distribution Focal Loss
DFL_WEIGHT = 0.25

# Bounding Box Loss
BBOX_LOSS_TYPE = GIoULoss
BBOX_LOSS_WEIGHT = 2.0

[QUANTIZER]

# Quantization method
NAME = MctKeras

BATCH_SIZE = 14

CALIB_ITERATIONS = 20


[VALIDATOR]

# Validator for object detection models
NAME = KerasObjectDetectionValidator
SCORE_THRESHOLD = 0.35
